"""unified user roles

Revision ID: 16b647d2bca8
Revises: 1afc3489eecf
Create Date: 2025-11-02 17:42:15.183026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b647d2bca8'
down_revision = '1afc3489eecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preferred_payment_method', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_trips', sa.Integer(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('drivers_license_number_key', 'drivers', type_='unique')
    op.drop_constraint('drivers_vehicle_plate_number_key', 'drivers', type_='unique')
    op.drop_index('ix_drivers_email', table_name='drivers')
    op.drop_index('ix_drivers_phone', table_name='drivers')
    op.create_foreign_key(None, 'drivers', 'users', ['id'], ['id'])
    op.drop_column('drivers', 'email')
    op.drop_column('drivers', 'name')
    op.drop_column('drivers', 'avatar_url')
    op.drop_column('drivers', 'phone')
    op.drop_column('drivers', 'hashed_password')
    op.add_column('ratings', sa.Column('rater_id', sa.UUID(), nullable=False))
    op.add_column('ratings', sa.Column('rated_id', sa.UUID(), nullable=False))
    op.add_column('ratings', sa.Column('rater_role', sa.Enum('RIDER', 'DRIVER', name='ratingparticipanttype'), nullable=False))
    op.add_column('ratings', sa.Column('rated_role', sa.Enum('RIDER', 'DRIVER', name='ratingparticipanttype'), nullable=False))
    op.drop_constraint('unique_trip_rating', 'ratings', type_='unique')
    op.create_unique_constraint('unique_trip_rating', 'ratings', ['trip_id', 'rater_id', 'rated_id', 'rater_role', 'rated_role'])
    op.drop_constraint('ratings_rater_driver_id_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_rated_driver_id_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_rated_user_id_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_rater_user_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'users', ['rated_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['rater_id'], ['id'])
    op.drop_column('ratings', 'rated_driver_id')
    op.drop_column('ratings', 'rated_user_id')
    op.drop_column('ratings', 'rater_driver_id')
    op.drop_column('ratings', 'rater_user_id')
    op.drop_constraint('trips_driver_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['driver_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.Enum('RIDER', 'DRIVER', 'BOTH', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_driver_id_fkey', 'trips', 'drivers', ['driver_id'], ['id'])
    op.add_column('ratings', sa.Column('rater_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('rater_driver_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('rated_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('rated_driver_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_rater_user_id_fkey', 'ratings', 'users', ['rater_user_id'], ['id'])
    op.create_foreign_key('ratings_rated_user_id_fkey', 'ratings', 'users', ['rated_user_id'], ['id'])
    op.create_foreign_key('ratings_rated_driver_id_fkey', 'ratings', 'drivers', ['rated_driver_id'], ['id'])
    op.create_foreign_key('ratings_rater_driver_id_fkey', 'ratings', 'drivers', ['rater_driver_id'], ['id'])
    op.drop_constraint('unique_trip_rating', 'ratings', type_='unique')
    op.create_unique_constraint('unique_trip_rating', 'ratings', ['trip_id', 'rater_user_id', 'rater_driver_id', 'rated_user_id', 'rated_driver_id'])
    op.drop_column('ratings', 'rated_role')
    op.drop_column('ratings', 'rater_role')
    op.drop_column('ratings', 'rated_id')
    op.drop_column('ratings', 'rater_id')
    op.add_column('drivers', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_index('ix_drivers_phone', 'drivers', ['phone'], unique=False)
    op.create_index('ix_drivers_email', 'drivers', ['email'], unique=False)
    op.create_unique_constraint('drivers_vehicle_plate_number_key', 'drivers', ['vehicle_plate_number'])
    op.create_unique_constraint('drivers_license_number_key', 'drivers', ['license_number'])
    op.drop_table('riders')
    # ### end Alembic commands ###
