"""support driver ratings

Revision ID: 1afc3489eecf
Revises: 7a994a330c81
Create Date: 2025-11-01 18:06:19.939477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afc3489eecf'
down_revision = '7a994a330c81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rater_user_id', sa.UUID(), nullable=True))
    op.add_column('ratings', sa.Column('rater_driver_id', sa.UUID(), nullable=True))
    op.add_column('ratings', sa.Column('rated_driver_id', sa.UUID(), nullable=True))
    op.alter_column('ratings', 'rated_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('unique_trip_rating', 'ratings', type_='unique')
    op.create_unique_constraint('unique_trip_rating', 'ratings', ['trip_id', 'rater_user_id', 'rater_driver_id', 'rated_user_id', 'rated_driver_id'])
    op.drop_constraint('ratings_rater_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'drivers', ['rater_driver_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'drivers', ['rated_driver_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['rater_user_id'], ['id'])
    op.drop_column('ratings', 'rater_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rater_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_rater_id_fkey', 'ratings', 'users', ['rater_id'], ['id'])
    op.drop_constraint('unique_trip_rating', 'ratings', type_='unique')
    op.create_unique_constraint('unique_trip_rating', 'ratings', ['trip_id', 'rater_id', 'rated_user_id'])
    op.alter_column('ratings', 'rated_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ratings', 'rated_driver_id')
    op.drop_column('ratings', 'rater_driver_id')
    op.drop_column('ratings', 'rater_user_id')
    # ### end Alembic commands ###
