"""split drivers from users

Revision ID: 7a994a330c81
Revises: 868d19c2b1f8
Create Date: 2025-11-01 15:29:05.490310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a994a330c81'
down_revision = '868d19c2b1f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('drivers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('drivers', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('drivers', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('drivers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('drivers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('total_trips', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('total_ratings', sa.Integer(), nullable=True))
    op.drop_constraint('drivers_user_id_key', 'drivers', type_='unique')
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=True)
    op.drop_constraint('drivers_user_id_fkey', 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'user_id')
    op.drop_constraint('trips_driver_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_driver_id_fkey', 'trips', 'users', ['driver_id'], ['id'])
    op.add_column('drivers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('drivers_user_id_fkey', 'drivers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.create_unique_constraint('drivers_user_id_key', 'drivers', ['user_id'])
    op.drop_column('drivers', 'total_ratings')
    op.drop_column('drivers', 'total_trips')
    op.drop_column('drivers', 'rating')
    op.drop_column('drivers', 'is_active')
    op.drop_column('drivers', 'avatar_url')
    op.drop_column('drivers', 'name')
    op.drop_column('drivers', 'hashed_password')
    op.drop_column('drivers', 'email')
    op.drop_column('drivers', 'phone')
    # ### end Alembic commands ###
